### ISSUE TITLE
영상 yolov5+pytorch 적용

### ISSUE THREAD

**Issue by dyjs-js** [dyjs-js/etg2022WISET#2]
본인이 직접 촬영한 영상으로 yolov5 적용 후 피드백

기한 : 8월 25일 목요일

**Comment by hahory** [comment]
https://user-images.githubusercontent.com/85267081/186554802-428dec5b-6fab-4941-8a35-845fd3dcdeb8.mp4

2600여장의 이미지로 만든 학습모델 사용했습니다.
횡단보도 건너편 pole등은 인식하는 반면 건너편 차를 인식하지 못하거나 가까이 있는 둥근 화분은 인식 못하네요.. 유모차를 traffic뭘로 인식하기도 했네요;;; 카테고리 클래스 수를 줄이든지, 데이터 양을 더 늘리던지 재학습이 필요해보입니다..
그리고 사진찍을 땐 제대로 찍었는데 모델에서 출력되는 과정에서 영상이 뒤집어진 걸 제가 다시 회전시킨거라서 label이 다 뒤집혀져 있으니 참고하세요^^; 출력 설정을 찾아보고 해결해야할 거 같아요..

**Comment by dyjs-js** [comment]
2161개의 이미지 이용
img 416 batch 16 epochs 200

저도 은정님 처럼 모델학습하고 출력되면서 영상이 180도 회전이 됐습니다.. 또한 제가 동영상을 좀 천천히 찍었어야 했는데 테스트용 동영상도 제대로 못찍은거같구요. :( 
내일 다시 동영상 찍어서 학습 적용 해보고 재 업로드하겠습니다.


https://user-images.githubusercontent.com/59755470/186718440-53ae5d10-357c-4648-84c2-5cd7dad12e6e.mp4

**Comment by iseoyeong** [comment]
<img width="527" alt="화면 캡처 2022-08-26 104232" src="https://user-images.githubusercontent.com/105969302/186798697-6aadf2aa-12c7-4f71-b470-61f8fb9d954c.png">

<img width="527" alt="화면 캡처 2022-08-26 103840" src="https://user-images.githubusercontent.com/105969302/186798258-1c0aa3aa-9938-47c6-aaeb-ebd5aa0ef120.png">

회의 전에 학습한 모델로 영상 인식했었던 결과물입니다. 첫 번째 사진처럼 각도가 바닥으로 갔을 때 바닥 부분도 car로 인식되는 등 부정확하게 인식되었습니다.

**Comment by Kimsunjeung** [comment]
https://user-images.githubusercontent.com/110511488/186854592-853d07c3-1fcc-4df6-8686-ed0730c2e9f0.mp4

4개 object 기반으로 했는데.... 인터넷에 있는 영상 클립으로 detect 한 결과에요~

**Comment by dyjs-js** [comment]
전체 확인했습니다. 감사합니다.

**Comment by dyjs-js** [comment]
전체 확인했습니다. 감사합니다.
